### ISSUE TITLE
WebApi ODATA: createRef() - Issues with relative path

### ISSUE THREAD

**Issue by Jithinkraju** [xuzhg/WebApiSample#3]
While using createRef(), if we give relative path in request body, URI comes as null. However, if we give full path, everything works as expected.

![1](https://cloud.githubusercontent.com/assets/18664953/14792759/a6394b1c-0ad0-11e6-8c16-7fc3c34f2f50.jpg)

![2](https://cloud.githubusercontent.com/assets/18664953/14792805/e0ef72d6-0ad0-11e6-9d5a-025d02f09df6.jpg)

Any comments or pointers on this please?

Best Regards
Jithin

**Comment by xuzhg** [comment]
The link payload should be one of the below content:
1.Absolute URIs, or
2.relative URIs, but "@odata.context" annotation must be on the payload.

So, as an example;

If the link value only has the relative Uri as below, it will be failed and the  link  parameter in the action  CreateRef  is  null .
  {"@odata.id":"Orders(2)"}  

Otherwise, if the payload is as below:

 {"@odata.context":"http://localhost/odata/$metadata","@odata.id":"Orders(2)"} 

It should be successful. 

I copied from https://github.com/OData/WebApi/issues/699

**Comment by Jithinkraju** [comment]
Thank you!

Best Regards,

Jithin Raju
